"""Constants for the detection package."""

DEFAULT_INFERENCE_DEVICE = "cpu"
DEFAULT_INFERENCE_IMGSZ = 640
DEFAULT_INFERENCE_CONF = 0.25

DEFAULT_BOX_COLOR = [255, 0, 0]
DEFAULT_BOX_THICKNESS = 4
DEFAULT_LABEL_BG_COLOR = [255, 0, 0]
DEFAULT_LABEL_TEXT_COLOR = [255, 255, 255]
DEFAULT_FONT_SIZE = 18
DEFAULT_LABEL_PADDING = [4, 2]
