name: CI/CD for the App

on:
  push

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the repository
      - name: Checkout the repo
        uses: actions/checkout@v4

      # 2) Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ai-people-detector:local .

      # 3) Check if tests exist
      - name: Check tests presence
        id: check_tests
        run: |
          if [ -d tests ] && find tests -type f -name "test_*.py" | grep -q .; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      # 4) Run tests inside Docker
      - name: Run tests inside Docker
        if: steps.check_tests.outputs.exists == 'true'
        run: |
          docker run --rm ai-people-detector:local python -m unittest discover -s tests -p "test_*.py"

      # 5) Skip tests if none found
      - name: Skip tests (no test files found)
        if: steps.check_tests.outputs.exists == 'false'
        run: echo "No test files found in ./tests — skipping unit tests."
